<div style="float: right; margin: 5px"><img src="images/identite.jpg" alt="The db0 company" /></div>
<div class="p">Bonjour et bienvenue, chers visiteurs !<br />
Ce site a pour but de me présenter sous tout les angles : personnels, proffessionels et loisirs. Ci dessous une vision générale de moi. Pour plus de détails, les sous-catégories ci-dessus.</div><br />

<div class="p">Je m'appelle Barbara Lepage, née le 30/05/1991 à Nice.</div>
<div class="p">J'ai suivi une scolarité des plus banales, passant par une classe européene de la 6ème à la 3ème (Italien commencé en 6ème + voyages en Italie) puis en 2nde l'option ISI (Initiation aux sciences de l'ingénieur) et enfin un Baccalauréat Scientifique - Sciences de la vie et de de la terre Spécialité Mathématiques.</div><br />
<div class="p">J'entre dès l'an prochain à l'école d'informatique Epitech. J'ai choisi cette école pour sa pédagogie autonome et la vision que j'avais de  mes études dans les voies de l'informatique. Pourquoi l'informatique ? J'ai eu la chance d'avoir des parents m'ayant éduquée à avoir une activité active et non pas passive, et me faisaient donc préférer "l'ordinateur" plutôt que "la télé". C'est donc depuis mon plus jeune âge que je vis avec l'informatique, et poursuivre dans cette voie me parraît donc évident. À la fin de mon cursus, je n'ai pas encore décider concrétement de ce que je voudrais faire, mais je pense grâce à cette école pouvoir me spécialiser dans ce qui me plaît vraiment.</div><br />
<div style="float: left; margin: 5px"><img src="images/avatar.png" alt="The db0 company" /></div>
<div class="p">Je vis depuis toujours à Nice auprès de mes parents, et j'ai un frère de 4 ans de moins que moi. J'ai aimé vivre à Nice, puisque c'est une ville très attirante et ensolleillée. Pour mes études, cependant, je démménage à Paris. Me voilà donc aujourd'hui parisienne pour une durée minimum de 5 ans (mon cursus).</div>
<div class="p">En dehors de ma scolarité, je pratique peu d'activité sportive (fréquent pour ceux qui aiment l'informatique), mais je suis "touche-à-tout" et très curieuse. J'ai fait beaucoup de Basket-ball, du théâtre, du journalisme, du cinéma, et surtout du dessin. Je ne peux pas me traiter d'"artiste" mais je passe mon temps à dessiner et j'aime beaucoup, ne désirant pas pour autant en faire ma vie.</div><br />
<div style="float: right; margin: 5px"><img src="images/moetan.png" alt="The db0 company" /></div>
<div class="p">Depuis quelques années, la culture "nippone" s'est emparée de moi. Je relie facilement cette passion avec celle de l'informatique et ai aujourd'hui plusieurs site web sur ce sujet. Je suis à la charge d'une équipe de fansub (sous-titrage bénévole d'animation japonaise dans le but de promouvoir cette culture en France), ainsi qu'un site de téléchargement direct d'animes, un site de streaming, et pleins d'autres. Mon projet est de créer une association proposant en libre service des karaokés en streaming.</div>
<div class="p">Ma passion pour la jap'anime ne s'arrête pas là, et je pratique réguliérement une activité appellée "cosplay". Composé de "costume" et "playing", cette activité consiste à réaliser soi-même le costume d'un personnage de jeu vidéo/manga et de jouer son rôle (acteur) pendant des évennements jap'animes (par exemple, Epitanime ou Japan Expo).</div><br />
<div class="p">Pour finir, je suis quelqu'un de très ouvert, très curieux, et à l'écoute des autres. Je n'irait pas jusqu'à me prétendre "hyperactive", mais je suis constamment à la recherche de nouveaux horizons, j'ai toujours beaucoup de projets en tête et en réalise la plupart. J'ai des aptitudes à gérer une équipe et à prendre des responsabilités. Je suis quelqu'un de timide au départ, mais qui sait se lancer quand il le faut.</div><br />
<div class="right">Barbara de mon prénom ou db0 de mon pseudo.</div>